### ISSUE TITLE
大佬这个docker也会运行fake2和helloworld的库吗

### ISSUE THREAD

**Issue by yufeiyang2008** [wudongdefeng/jd_py#2]
fake2 = 'https://github.com.cnpmjs.org/shufflewzc/faker2.git'
    hello = 'https://github.com.cnpmjs.org/JDHelloWorld/jd_scripts'

**Comment by wudongdefeng** [comment]
就用我的tem-update就够了，可以运行

**Comment by yufeiyang2008** [comment]
可以自动提交助力码吗
